#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2


# This SITL vehicle is flown purely over uXRCE-DDS/ROS2 offboard control -
# no MAVLink GCS (QGroundControl etc.) ever connects, so vehicle_status.
# gcs_connection_lost stays true from boot onward (Commander.cpp default).
# NAV_DLL_ACT > 0 makes a data link mandatory to arm in ANY mode, which
# would permanently block arming here. Disabled for this SITL airframe;
# real-hardware antidrone.px4board builds are unaffected by this file.
param set-default NAV_DLL_ACT 0

# Flip-test maneuver: FailureDetector disarms at 60 deg roll/pitch by default,
# which trips mid-flip regardless of the rate-setpoint control path. Raised
# above the flip's full-rotation envelope so the offboard flip scripts under
# test_maneuver/ don't get an uncommanded disarm partway through.
param set-default FD_FAIL_R 180
param set-default FD_FAIL_P 180